services:
  geocensus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geocensus-dashboard
    restart: always
    ports:
      - "3000:80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true